server:
  port: 8082
spring:
  application:
    name: lagou-service-email
  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    username: creasylai_public@126.com
    password: HLXECDBRRQFFCOBA
    host: smtp.126.com
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
