server:
  port: 9006
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:creasylai19/spring-cloud-config.git
          timeout: 5
#如果本地有被改过的话，强制从git服务器拉取更新
          force-pull: true
#          uri: https://github.com/creasylai19/spring-cloud-config.git
#使用https协议时，需要用户名密码
#          username: creasylai19@gmail.com
#          password: ${password}
  application:
    name: lagou-service-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}